{
  "PublicDateAtUSN": "0001-01-01T00:00:00Z",
  "CRD": "0001-01-01T00:00:00Z",
  "Candidate": "CVE-2025-32414",
  "PublicDate": "2025-04-08T03:15:00Z",
  "References": [
    "https://www.cve.org/CVERecord?id=CVE-2025-32414"
  ],
  "Description": "In libxml2 before 2.13.8 and 2.14.x before 2.14.2, out-of-bounds memory access can occur in the Python API (Python bindings) because of an incorrect return value. This occurs in xmlPythonFileRead and xmlPythonFileReadRaw because of a difference between bytes and characters.",
  "UbuntuDescription": "",
  "Notes": [
    "mdeslaur\u003e as of 2025-04-09, the fix is still being discussed in the bug"
  ],
  "Bugs": [
    "https://gitlab.gnome.org/GNOME/libxml2/-/issues/889"
  ],
  "Priority": "medium",
  "DiscoveredBy": "",
  "AssignedTo": "",
  "Patches": {
    "libxml2": {
      "devel": {
        "Status": "needs-triage",
        "Note": ""
      },
      "esm-infra-legacy/trusty": {
        "Status": "needs-triage",
        "Note": ""
      },
      "esm-infra/bionic": {
        "Status": "needs-triage",
        "Note": ""
      },
      "esm-infra/xenial": {
        "Status": "needs-triage",
        "Note": ""
      },
      "focal": {
        "Status": "needs-triage",
        "Note": ""
      },
      "jammy": {
        "Status": "needs-triage",
        "Note": ""
      },
      "noble": {
        "Status": "needs-triage",
        "Note": ""
      },
      "oracular": {
        "Status": "needs-triage",
        "Note": ""
      },
      "upstream": {
        "Status": "needs-triage",
        "Note": ""
      }
    }
  },
  "UpstreamLinks": {}
}