{
  "PublicDateAtUSN": "0001-01-01T00:00:00Z",
  "CRD": "0001-01-01T00:00:00Z",
  "Candidate": "CVE-2025-2953",
  "PublicDate": "2025-03-30T16:15:00Z",
  "References": [
    "https://www.cve.org/CVERecord?id=CVE-2025-2953",
    "https://github.com/pytorch/pytorch/issues/149274",
    "https://github.com/pytorch/pytorch/issues/149274#issue-2923122269",
    "https://vuldb.com/?ctiid.302006",
    "https://vuldb.com/?id.302006",
    "https://vuldb.com/?submit.521279"
  ],
  "Description": "A vulnerability, which was classified as problematic, has been found in PyTorch 2.6.0+cu124. Affected by this issue is the function torch.mkldnn_max_pool2d. The manipulation leads to denial of service. An attack has to be approached locally. The exploit has been disclosed to the public and may be used.",
  "UbuntuDescription": "",
  "Notes": null,
  "Bugs": null,
  "Priority": "medium",
  "DiscoveredBy": "",
  "AssignedTo": "",
  "Patches": {
    "pytorch": {
      "devel": {
        "Status": "needs-triage",
        "Note": ""
      },
      "esm-apps/jammy": {
        "Status": "needs-triage",
        "Note": ""
      },
      "focal": {
        "Status": "DNE",
        "Note": ""
      },
      "jammy": {
        "Status": "needs-triage",
        "Note": ""
      },
      "noble": {
        "Status": "DNE",
        "Note": ""
      },
      "oracular": {
        "Status": "needs-triage",
        "Note": ""
      },
      "upstream": {
        "Status": "needs-triage",
        "Note": ""
      }
    }
  },
  "UpstreamLinks": {}
}